#ifndef ESTIMATORS_GLOBAL_H
#define ESTIMATORS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ESTIMATORS_LIBRARY)
#  define ESTIMATORSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ESTIMATORSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ESTIMATORS_GLOBAL_H
