#ifndef SOURCE_LOCALIZATION_GLOBAL_H
#define SOURCE_LOCALIZATION_GLOBAL_H

#include <QtCore/qglobal.h>
#include <stdexcept>

#if defined(SOURCE_LOCALIZATION_LIBRARY)
#  define SOURCE_LOCALIZATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SOURCE_LOCALIZATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SOURCE_LOCALIZATION_GLOBAL_H
